:experimental:
:imagesdir: imgs/
ifdef::env-github[]
:icons:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

TIP: Supports Windows and Linux (Wine only; until Valve uses link:https://github.com/Joshua-Ashton/dxvk-native[dxvk-native] instead of ToGL)

== Used custom configs previously?

. Steam -> Library -> Team Fortress 2 -> Uncheck/disable "Keep games saves in the Steam Cloud for Team Fortress 2"
. Local Files -> Browse... 
. \tf -> \custom -> then search for `.cfg`; check their contents, then move or remove those (.cfg) files.
. Go up a directory (back out) -> \cfg -> delete "config.cfg"
. Set in TF2's Launch Options: `-novid -autoconfig -default +host_writeconfig config.cfg full +mat_savechanges +quit`
. Launch/Run/Play TF2, it will automatically exit
. Remove those launch options and proceed to Setup

== Setup
. Replace Launch Options with:
- `-novid -nodns -nostartupsound -nohltv -nojoy -nobreakpad -nosteamcontroller -noquicktime -precachefontintlchars -disable_d3d9_hacks -nomaster -nowatchdog -nocrashdialog -hushsteam`
- Linux specific additions: `-glslcontrolflow -arbmode`
. Go to the link:https://github.com/high-brow/Vusaline/releases[releases section] and grab the newest zip, then extract that zip and make sure all it's contents are in the same folder.
. Once everything is unzipped, run **`vusalo_setup.bat`** and everything should be installed automatically! If you use a custom TF2 directory, edit the .bat file and copy paste your directory as indicated
. That's it! Go out there and play TF2!

== Extra steps
. Use **`user\options.cfg`** to configure it further
. Use class configs? Move them to `Team Fortress 2\tf\cfg\class`
. Play on `sv_pure` servers? Add **`use_no_gibs.vpk`** to `Team Fortress 2\tf\custom` when disabling gibs
. Use link:https://bitsum.com[Process Lasso] or link:https://processhacker.sourceforge.io/nightly.php[Process Hacker] to set hl2.exe's affinity to always exclude CPU 0 (if you only see 4 checkboxes, avoid this), and hl2.exe's priority to High
. Don't like something about Vusalo? Change it! Add the `zzz_vusalo_base` folder to `Team Fortress 2\tf\custom` to reconfigure it! Then, run **`make_vusalo_base_vpk.bat`**

== Avoid the following
* Putting spaces in an option, such as `dualcore = 1`(incorrect) instead of `dualcore=1`(correct)
* Using transparent viewmodel support in your HUD
- Potential to mess with world props: https://youtu.be/fg5eBkmVS1c
- Adds another HUD animation, which will impact frametimes
* Using `allow_crash_reporting=1` without removing the `-nobreakpad` launch option
* Using `allow_file_transfers=1` without using `sprays=1;allow_file_downloads=1` in **`user/options.cfg`**
* The following mods will cause instability:
- link:https://gamebanana.com/mods/206443[Robot animation fixes (by sigsegv)]

* Don't execute commands you don't know, it can get you banned on community servers if you execute say "fm_attackmode" (which doesn't exist, but a cheat used it at some point)

== autoexec2.cfg - where you put your custom changes, such as aliases and convars
* Change Motion Blur
- `mat_motion_blur_enabled 1` then mess with `mat_motion_blur_strength`

* Change contrast for Fullscreen mode (only)
- `mat_monitorgamma`
- Allowed range: From `1.6` up to `2.6`

* Adjust Killfeed time
- `hud_deathnotice_time 6.0` = 6.0 seconds

* Adjust Killstreak feed time
- `cl_hud_killstreak_display_time 3.0` = 3.0 seconds

* If in need of more FPS, set the following for GPUs with a "G3D Mark" of <=1365
* Turn off anisotropic filtering for textures (makes textures low-res looking & ugly)
- `mat_forceaniso 1`

== Compared to other configs
* Focused on game stability, CPU time reduction, and stable/smooth frametimes
* Measures with a profiler (very accurate), instead of FPS/Frames Per Second
* Config files are easy to read through
* Bad preferences are blocked off
* Insane loading time reductions (no FPS impact)
* Less memory usage (no FPS impact)

== Decision making
`bind F1"";bind F2""` +
"f2" = "show_quest_log" : can break voting no on a player; the same is for F1

`net_maxpacketdrop 5000` +
Dropping too many packets in a row will break lag compensation, with Valve's default of 5000 packets being the cut-off point; `cl_fullupdate` won't fix lag compensation, a `retry` is needed

NOTE: The game doesn't do a `cl_fullupdate` if you have packet loss, and also doesn't for class changes; see for yourself with `developer 4;contimes 50` +
A single `cl_fullupdate` is needed (only at end of connecting to a server), any past that will break lag compensation

`net_maxcleartime 4.0`
[source,cpp]
----
// If the network connection hasn't been active in this many seconds, display some warning text.
#define CONNECTION_PROBLEM_TIME		4.0f	// assume network problem after this time
----
`cl_timeout 30` +
Disconnects after dropping 5000 packets in a row

`low_fps=0"cl_cmdrate 100;cl_updaterate 66"` +
If the FPS is below the updaterate often (below 66FPS for 66 updaterate), hit registration accuracy is noticeably reduced. 100 tickrate servers be damned, as 100 tickrate makes no noticeable difference (tested with a good aimbot) in accuracy

`net_blockmsg 0`
[source,cpp]
----
// From CS:GO
static ConVar net_blockmsg( "net_blockmsg", "0", FCVAR_CHEAT, "Discards incoming message: <0|1|name>" ); // "none" here is bad, causes superfluous strcmp on every net message
----

`tf_scoreboard_ping_as_text 1` +
Less FPS intensive, and provides more useful information than coloured bars

No usage of `cmd` +
I haven't reversed this to see if it helps

`net_queued_packet_thread 581304` +
Less chance of packet rejection (causes prediction errors; hitreg inaccuracy) from the server due to forcefully clumping packets together, instead of sending packets individually on each frame (at 0, but can happen with 1)

`net_splitrate 1` +
Packet fragmentation optimally is avoided, but whenever needed, this will stop complete network stalls from occuring

`fps_max 0` +
Frame limit using RTSS or nVidia's "Max Frame Rate" instead, as they're more consistent.

WARNING: Don't leave the game FPS uncapped while playing normally, memory leaking will occur. However, it's desirable to uncap FPS while profiling

`r_occlusion 1` +
Meant to improve performance by manually selecting which areas to occlude. Performance issues caused by this are due to poor map optimisation and/or hardware.

`cl_pred_optimize 2` +
Don't trust engine pred to be accurate enough (despite no packet loss), keep re-calculating engine prediction

`mod_dynamicunloadtime 600` +
Use highest possible wait time to unload unused dynamic models (player cosmetics); good if a player with a specific cosmetic set leaves, then another player joins more than 150 (default) seconds later with that same cosmetic set.

`hud_escort_interp 0.2` +
Interpolating the Payload Cart HUD element causes it to overshoot in distance, which is helpful in high ping and/or high packet loss situations; value of 0.2 doesn't undershoot for low ping with zero packet loss

`tf_mm_custom_ping 350;tf_mm_custom_ping_enabled 0` +
Party System is very sensitive to latency, it'll put you in low ping servers regardless

`rate 1048576` +
Artifical network delays don't fix the central issue(s) with packet loss; `loss_severity` was added to change how packets are sent & received in the first place to lessen packet loss impact

`m_mousespeed 0;alias m_mousespeed""` +
Use only https://github.com/a1xd/rawaccel for mouse acceleration!

`mat_forcehardwaresync 1;alias mat_forcehardwaresync` +
Other game engines sync the CPU and GPU frames closely (such as UE4), which will reduce input latency/lag (more noticeable at low FPS)

`w10_mouse=1"m_limitedcapture_workaround 1"` +
Less CPU time spent on Input (less FPS drop during mouse movement) for Windows 10 in Fullscreen mode

`m_rawinput 1` +
Read the thread content and posts link:https://www.mouse-sensitivity.com/updates/updates/csgo-m_rawinput-vs-rinput-r149[here]

**`tr_walkway_fix.cfg`** +
Local servers are always inaccurate; SRCDS is always accurate, even if hosted on the PC you're running TF2 from
Despite this, a single **required** convar change for this map is included for convenience

`in_usekeyboardsampletime 0` +
While using keyboard look, this convar set to 1 portrays an inaccurate view for +left & +right, and makes key inputs noticeably delayed

`tf_scoreboard_mouse_mode 1` +
Ability to quickly view profiles and mute players; 1 instead of 2 to discourage spamming the scoreboard key (out of habit)

`tf_chat_popup_hold_time 10` +
The lower `tf_chat_popup_hold_time` is, the higher chances of crashing from party chat message spamming +
0 is off; party messages stay on the main menu forever, but has the least chance of crashing the game

`tf_inspect_hint_count 11` +
Specifies how many times you've been given the Weapon Inspection Hint, with 11 times turning off the Weapon Inspection Hint

Not using `-r_emulate_gl` +
Tells the game that ToGL is being used (when it isn't); includes hacks that reduce FPS for both OpenGL and DirectX

`-disable_d3d9_hacks` +
If some or all of TF2's DirectX9 hacks still apply for the latest graphical drivers of GPUs still supported by Windows 10, that could potentially cause bugs seemingly no-one else has, and decrease FPS

`alias vr_support=0"mat_vrmode_adapter -1"` +
Fixes inability to go into Fullscreen mode if VR was enabled; this assumes a VR headset isn't used anymore for TF2, as that's the bug it fixes

What is the point of rimlight? +
link:https://www.youtube.com/watch?v=C-47CwPYL3w&t=657s[Well Developer Commentary]

`con_filter_enable 1; con_filter_text_out "ad-hoc"` +
Supresses warnings from using `-hushsteam` launch argument (to hide your IP address if hosting a local server)

Why Vusaline? +
Vusaline is a project that aims to continue and improve Vusalo with the intention of adding them to the original. You could think of it as an "experimental" version of Vusalo, however Vusaline also includes a lot of changes that prevent it from going outdated

== Shoutouts
* link:https://github.com/high-brow[Spookbuster] because I'm an egoist
* link:https://github.com/Iazos[Iazos] for starting the project
* link:https://github.com/JarateKing[JarateKing] for being a wizard
* The link:https://developer.valvesoftware.com[Valve Developer Community] for their extensive documentation of commands and variables