:experimental:
:imagesdir: imgs/
ifdef::env-github[]
:icons:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

TIP: Supports Windows and Linux (Wine only; until Valve uses link:https://github.com/Joshua-Ashton/dxvk-native[dxvk-native] instead of ToGL).

== Used custom configs previously?
. Steam -> Library -> Team Fortress 2 -> Uncheck/disable "Keep games saves in the Steam Cloud for Team Fortress 2".
. Local Files -> Browse... 
. From there, go to `tf\custom` and search for `.cfg` files; then, check their contents, and move or remove those (.cfg) files accordingly.
. Go up a directory (back out) -> \cfg -> delete **`config.cfg`**.
. Unzip **`full_reset.7z`** and run **`reset_configs.bat`** (NOTE: This will reset your binds and settings, backing them up is recommended!).
. Once TF2 starts up, wait until it closes automatically, then proceed to *Setup*.

== Setup
. Replace launch options with:
- `-novid -nodns -nostartupsound -nohltv -nojoy -nobreakpad -nosteamcontroller -noquicktime -precachefontintlchars -disable_d3d9_hacks -nomaster -nowatchdog -nocrashdialog -hushsteam`.
- Linux specific additions: `-glslcontrolflow -arbmode`.
. Go to the link:https://github.com/high-brow/Vusaline/releases[releases section] and grab the newest zip, then extract that zip and make sure all it's contents are in the same folder.
. Once everything is unzipped, run **`vusalo_setup.bat`** and everything should be installed automatically! If you use a custom TF2 directory, edit the .bat file and copy and paste your directory as indicated (remember to leave the quotes!).
. That's it! Go out there and play TF2!

== Extra steps
. Use **`user\options.cfg`** to configure Vusaline.
. Use class configs? Move them to `Team Fortress 2\tf\cfg\class`.
. Use a custom autoexec? You can find it as autoexec2.cfg. If you haven't, you can create it to make aliases and change cvars like:
* Change Motion Blur:
- `mat_motion_blur_enabled 1` then mess with `mat_motion_blur_strength`
* Change contrast for fullscreen mode (only):
- `mat_monitorgamma`
- Allowed range: From `1.6` up to `2.6`
* Adjust Killfeed time (in seconds):
- `hud_deathnotice_time`
* Adjust Killstreak feed time (in seconds):
- `cl_hud_killstreak_display_time`
* If in need of more FPS, set the following for GPUs with a "G3D Mark" of <=1365:
- Turn off anisotropic filtering for textures (makes textures low-res looking & ugly)
- `mat_forceaniso 1`
. Instead of using `-high`, use link:https://bitsum.com[Process Lasso] or link:https://processhacker.sourceforge.io/nightly.php[Process Hacker] to set hl2.exe's affinity to always exclude CPU 0 (if you only see 4 checkboxes, avoid this), and hl2.exe's priority to High.
. Don't like something about Vusalo? Change it! Unpack **`vusalo_base.7z`** and place it in `Team Fortress 2\tf\custom` to reconfigure it! Once you're done, run **`make_vusalo_base_vpk.bat`** in `Team Fortress 2\Vusalo`.

== Avoid the following
* Putting spaces in **`options.cfg`**, such as `dualcore = 1`(incorrect) instead of `dualcore=1`(correct).
* Using transparent viewmodel support in your HUD:
- Potential to mess with world props: https://youtu.be/fg5eBkmVS1c
- Adds another HUD animation, which will impact frametimes.
* Using `block_crash_reporting=0` without removing the `-nobreakpad` launch option.
* The following mods will cause instability:
- link:https://gamebanana.com/mods/206443[Robot animation fixes (by sigsegv)].
* Don't execute commands you don't know! It can get you banned on community servers if you execute say "fm_attackmode" (which doesn't exist, but a cheat used it at some point).

== About/FAQ
What is Vusalo? +
Vusalo is a (somewhat subjectivised) performance enhancer for TF2 that's based around improving stability, originally created by Iazos.

Why Vusaline? +
I started Vusaline with the intention to continue and improve Iazos' Vusalo. You could think of it as an "experimental" version of Vusalo, however Vusaline also includes a lot of changes that maintain it up-to-date with the current versions of TF2.

How does Vusalo compare to other configs? +
. It's focused on game stability, CPU time reduction, and stable/smooth frametimes.
. Measures/benchmarks are taken with a profiler (very accurate), instead of FPS/Frames Per Second.
. Config files are easy to read through.
. Bad preferences are blocked off.
. Massive improvements to loading times (no FPS impact).
. Reduced memory usage (no FPS impact).

Decision making +
You can find how many of Vusalo/Vusaline's decisions were taken link:https://github.com/high-brow/Vusaline/blob/master/decisions.adoc[here].

For VR users +
Go to `Team Fortress 2\Vusalo` and edit **`vusalo_file_operations.bat`**. On the 9th line, you should find `block_vr=1`; set it to `block_vr=0`. Then, run **`revert_vusalo_file_operations.bat`** and **`vusalo_file_operations`** afterwards.

For RijiN v1 users +
Remove the `-nobreakpad` launch option. If issues prevail, consider removing `-nosteamcontroller` (not necessary).

"The installer gives me an error!" +
Reextract **`Vusalo-master.zip`** and make sure all the extracted files are "as is" in the same folder (`Vusalo-master`). If there error persists, then this is most likely due to you having a custom TF2 install directory. Edit the batch file as described in step 3 of link:https://github.com/high-brow/Vusaline#setup[setup].

"I don't like how Vusaline does [X]!" +
Go to `Team Fortress 2\tf\custom\vusalo_configuration\cfg` and edit **`options.cfg`** to your linking. If you can't find what you're looking for there, then add it to **`autoexec2.cfg`** located in `Team Fortress 2\tf\cfg` (create it if it isn't already). If you're still unable to change what it is you want, then this is most likely a design choice. To learn more, please go link:https://github.com/high-brow/Vusaline/blob/master/decisions.adoc[here]. If you still wish to modify the configs, go to link:https://github.com/high-brow/Vusaline#extra-steps[xtra steps] and follow step 5.

"I want to uninstall this crap!" +
Simply follow link:https://github.com/high-brow/Vusaline#used-custom-configs-previously[these] steps!

== Shoutouts
* link:https://github.com/high-brow[Spookbuster] because I'm an egoist.
* link:https://github.com/Iazos[Iazos] for starting the original project.
* link:https://github.com/JarateKing[JarateKing] for being a wizard.
* The link:https://developer.valvesoftware.com[Valve Developer Community] for their extensive documentation of commands and variables.